services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix-code-recovery-api
    restart: unless-stopped
    ports:
      - "3035:3035"
      - PORT=3035
      - LOG_LEVEL=trace
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/opt/app/data
    networks:
      - netflix-recovery

networks:
  netflix-recovery:
    driver: bridge
